stages:
  - lint
  - typecheck
  - unit_test
ruff:
  stage: lint
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - ruff check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
ty:
  stage: typecheck
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - ty check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
pytest:
  stage: unit_test
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"