stages:
  - check
  - tests

lint:
  stage: check
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - ruff check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

format:
  stage: check
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - ruff format --check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

ty:
  stage: check
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - pip install --group server .
    - pip install --group client .
    - pip install --group worker .
    - ty check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

language-version:
  stage: check
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install --group devel .
    - vermin .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

pytest:
  stage: tests
  image: python:3.14
  script:
    - pip install --upgrade pip
    - pip install .
    - pip install --group devel .
    - pip install --group server .
    - pip install --group client .
    - pip install --group worker .
    - pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"