repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.14
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/allganize/ty-pre-commit
  rev: v0.0.39
  hooks:
    - id: ty-check
- repo: https://github.com/netromdk/vermin
  rev: v1.8.0
  hooks:
    - id: vermin