[build-system]
requires = ["uv_build~=0.11.7"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[project]
name = "mprun"
version = "0.0.1"
description = "Multi-Parameter Task Runner"
readme = "Readme.md"
requires-python = ">= 3.12"
license = "MIT"
license-files = ["LICENSE"]

authors = [
  {name = "Markus Sommer", email = "msommer@informatik.uni-marburg.de"}
]
maintainers = [
  {name = "Markus Sommer", email = "msommer@informatik.uni-marburg.de"}
]
classifiers = [
    "Development Status :: 3 - Alpha",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
]

dependencies = ["pydantic~=2.13.3"]

[dependency-groups]
server = [
    "uvicorn~=0.46.0",
    "fastapi~=0.136.1",
    "tinydb~=4.8.2",
    "python-multipart~=0.0.20",
]
client = [
    "typer~=0.25.0",
    "httpx~=0.28.1",
    "tomlkit~=0.14.0"
]
worker = [
    "httpx~=0.28.1",
]
dev = [
    "pre-commit~=4.6.0",
    "hatchling~=1.29.0",
    "ruff~=0.15.12",
    "ty~=0.0.32",
    "pytest~=9.0.3",
    "pytest-asyncio~=1.3.0",
    "hypothesis~=6.152.3",
    "vermin~=1.8.0",
    "pytest-cov~=7.1.0",
]

[project.urls]
Repository = "https://gitlab.uni-marburg.de/fb12/ag-freisleben/projects/mprun"

[project.scripts]
mprun_client = "mprun.client:client"
mprun_server = "mprun.server:cli"
mprun_worker = "mprun.worker:cli"

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 88
indent-width = 4

target-version = "py312"

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C",
    "D",
    "DTZ",
    "E",
    "EM",
    "EXE",
    "F",
    "FA",
    "FBT",
    "FLY",
    "FURB",
    "I",
    "ISC",
    "LOG",
    "N",
    "PGH",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PT",
    "PTH",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLOT",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT"
]
ignore = [
    "E501", # we no longer live in a world of 80 character terminals.
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    "S", # there's a bunch of things (like plenty of asserts) which are entirely normal for tests
    "PLR2004", # tests need to compare against known good ('magic') values
]
"mprun/client.py" = [
    "FBT", # that's just how CLI flags work...
]
"mprun/server.py" = [
    "FBT", # that's just how CLI flags work...
]
"mprun/worker.py" = [
    "FBT", # that's just how CLI flags work...
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.File", "fastapi.Form"]

[tool.ty.rules]
all = "error"
