"""Pydantic models for experiments, runs, and workers."""

from __future__ import annotations

from enum import Enum, StrEnum, auto
from itertools import product
from os import X_OK, access
from pathlib import Path
from time import time
from uuid import uuid4
from zipfile import ZIP_LZMA, ZipFile

import pytimeparse2
from pydantic import BaseModel, ValidationInfo, field_validator
from tomlkit import dump, load

from mprun.errors import ArchiveValidationError, InvalidParametersError
from mprun.types import ActiveState, RunId, SuccessState, TOMLScalar

EXPERIMENT_DEFINITION_NAME = "experiment_definition.toml"
EXPERIMENT_ARCHIVE_NAME = "experiment_archive.zip"


def _expand_parameters(
    params: dict[str, list[TOMLScalar]],
) -> list[dict[str, TOMLScalar]]:
    """Return the Cartesian product of all parameter lists as concrete parameter sets.

    Args:
        params (dict[str, list[TOMLScalar]]): Mapping of parameter names to their possible values.

    Returns:
        list[dict[str, TOMLScalar]]: One dict per combination, each mapping every parameter name
            to a single value. Covers all possible combinations.

    Raises:
        InvalidParametersError: If ``params`` is empty, any key is an empty string, or any
            value list is empty.
    """
    if not params:
        raise InvalidParametersError(reason="Empty parameters not allowed")

    for key, values in params.items():
        if not key:
            raise InvalidParametersError(
                reason="Parameter keys must not be empty string"
            )
        if not values:
            raise InvalidParametersError(reason="Parameter lists must not be empty")

    expanded: list[dict[str, TOMLScalar]] = []

    keys = list(params.keys())
    for values in product(*params.values()):
        expanded.append(dict(zip(keys, values, strict=True)))

    return expanded


class ValidationMode(Enum):
    """Different modes for validation of Experiments/ExperimentDefinitions.

    DATA_ONLY: Only validate Experiment data (contents of Experiment/ExperimentDefinition object).
    DATA_AND_FILES: Also validate Experiment files (check if filenames specified in Experiment actually exist).
    """

    DATA_ONLY = auto()
    DATA_AND_FILES = auto()


class ExperimentDefinition(BaseModel):
    """Minimal information needed to create a new Experiment.

    Attributes:
        name (str): Human-readable experiment name. Does not have to be unique.
        params (dict[str, list[TOMLScalar]]): Experiment parameters. Each key maps to a list of
            discrete TOML-serializable values (str, int, float, bool). Runs are generated by
            computing the Cartesian product of all parameter lists.
        executable (str): Name of the experiment's main executable. When loading from TOML, the
            file must exist in the same directory as the TOML definition.
        results (dict[str, str]): Files or directories to save after each run. Keys are paths
            on the worker's filesystem; values are the names they will have inside the results
            archive.
        timeout (int | None): Optional run timeout in seconds. If ``None``, runs may execute
            indefinitely.
        setup_executable (str | None): Optional executable to run before the main executable.
            When loading from TOML, the file must exist in the same directory as the TOML
            definition.
        environment_variables (dict[str, str] | None): Optional environment variables to set
            before executing the main executable.
        environment_files (dict[str, str] | None): Optional additional files or directories to
            copy to the worker's filesystem before execution. Each entry maps a source path
            (relative to the experiment directory) to a destination path on the worker.
    """

    name: str
    params: dict[str, list[TOMLScalar]]
    executable: str
    results: dict[str, str]
    timeout: int | None = None
    setup_executable: str | None = None
    environment_variables: dict[str, str] | None = None
    environment_files: dict[str, str] | None = None

    def dump_toml(self, file_path: Path) -> None:
        """Write this ExperimentDefinition to a TOML file.

        Args:
            file_path (Path): Destination path for the TOML file.
        """
        data = self.model_dump(exclude_none=True)
        with file_path.open("w", encoding="utf-8") as f:
            dump(data=data, fp=f)

    @classmethod
    def load_toml(
        cls, file_path: Path, validation_mode: ValidationMode
    ) -> ExperimentDefinition:
        """Load an ExperimentDefinition from a TOML file.

        Args:
            file_path (Path): Path to the TOML file to load.
            validation_mode (ValidationMode): Controls validation depth. See ``ValidationMode``
                for available modes.

        Returns:
            ExperimentDefinition: Parsed and validated instance.

        Raises:
            OSError: If reading the file fails.
            pydantic.ValidationError: If the file contents are not a valid ExperimentDefinition.
            ValueError: If a timeout string is present but cannot be parsed.
        """
        with file_path.open("r") as f:
            data = load(f).unwrap()

            if isinstance(data.get("timeout"), str):
                data["timeout"] = pytimeparse2.parse(
                    data["timeout"], raise_exception=True
                )

            if validation_mode == ValidationMode.DATA_ONLY:
                return cls.model_validate(data, strict=True)
            return cls.model_validate(data, strict=True, context=file_path.parent)

    @field_validator("executable", mode="after")
    @classmethod
    def validate_executable(cls, name: str, info: ValidationInfo) -> str:
        """Validate an executable name.

        When a directory path is provided via ``info.context``, checks that a file with the given
        name exists in that directory and is marked executable.

        Args:
            name (str): Executable filename only — not a full path. The full path is derived from
                ``info.context``.
            info (ValidationInfo): When provided, ``info.context`` must be a ``Path`` pointing to
                the directory containing the experiment's files.

        Returns:
            str: The validated executable name, unchanged.

        Raises:
            ValueError: If the context path is not a directory, the file does not exist, or the
                file is not marked executable.
        """
        if not isinstance(
            info.context, Path
        ):  # if no path is provided, there's no further evaluation to do.
            return name
        dir_path: Path = info.context
        if not dir_path.is_dir():  # the directory should actually be a directory...
            msg = f"{dir_path} not a directory"
            raise ValueError(msg)

        executable_path = dir_path / name
        if not executable_path.is_file(
            follow_symlinks=False
        ):  # a file with the name should exist
            msg = f"No such file: {executable_path}"
            raise ValueError(msg)
        if not access(executable_path, X_OK):  # the file should be marked executable
            msg = f"File {executable_path} not marked executable"
            raise ValueError(msg)

        return name

    @field_validator("setup_executable", mode="after")
    @classmethod
    def validate_setup(cls, name: str | None, info: ValidationInfo) -> str | None:
        """Validate the optional setup executable.

        When a name is provided, applies the same validation logic as ``validate_executable``.

        Args:
            name (str | None): Executable filename only — not a full path. ``None`` skips
                validation entirely.
            info (ValidationInfo): When provided, ``info.context`` must be a ``Path`` pointing to
                the directory containing the experiment's files.

        Returns:
            str | None: ``None`` if no name was given; otherwise the validated name, unchanged.

        Raises:
            ValueError: If the context path is not a directory, the file does not exist, or the
                file is not marked executable.
        """
        if name is None:  # if no name is given, then there's nothing to do
            return None
        return cls.validate_executable(
            name=name, info=info
        )  # if a name is given, the validation logic is the same as with the main executable.

    @field_validator("environment_files", mode="after")
    @classmethod
    def validate_env_files(
        cls, files: dict[str, str] | None, info: ValidationInfo
    ) -> dict[str, str] | None:
        """Validate the optional environment files mapping.

        Checks that each source file exists within the experiment directory. Destination paths
        are not validated.

        Args:
            files (dict[str, str] | None): Mapping of source filenames to destination paths,
                i.e. ``{file_name: copy_to}``. ``None`` skips validation entirely.
            info (ValidationInfo): When provided, ``info.context`` must be a ``Path`` pointing to
                the directory containing the experiment's files.

        Returns:
            dict[str, str] | None: ``None`` if no files were specified; otherwise the validated
                mapping, unchanged.

        Raises:
            ValueError: If the context path is not a directory or any source file does not exist.
        """
        if files is None:  # if no files were given, then there's nothing to do
            return None

        if not isinstance(
            info.context, Path
        ):  # if no path is provided, there's no further evaluation to do.
            return files
        dir_path: Path = info.context
        if not dir_path.is_dir():  # the directory should actually be a directory...
            msg = f"{dir_path} not a directory"
            raise ValueError(msg)

        for env_file in files:
            file_path = dir_path / env_file
            if not file_path.is_file(follow_symlinks=False):
                msg = f"No such file: {file_path}"
                raise ValueError(msg)

        return files

    def create_archive(self, experiment_toml: Path) -> Path:
        """Create archive for Experiment.

        Tries to create zip archive of all files specified in this ExperimentDefinition.
        Created archive will be located in same directory as files.

        Args:
            experiment_toml (Path): Path to the Experiment's TOML file. All other Experiment files need to be located in the same directory.

        Returns:
            Path: Path of the created archive.

        Raises:
            FileNotFoundError: If ``experiment_toml``, its parent directory, or any referenced file
                (``executable``, ``setup_executable``, entries in ``environment_files``) does not exist.
            PermissionError: If the archive destination directory is not writable, or any source
                file is not readable.
            OSError: For other I/O failures (e.g. disk full) during archive creation or file writes.
            lzma.LZMAError: If LZMA compression fails (rare; typically memory pressure or corrupt data).
        """
        directory = experiment_toml.parent
        archive_path = directory / EXPERIMENT_ARCHIVE_NAME
        with ZipFile(
            archive_path,
            mode="w",
            compression=ZIP_LZMA,
            allowZip64=True,
        ) as zf:
            zf.write(
                experiment_toml, EXPERIMENT_DEFINITION_NAME
            )  # add ExperimentDefinition itself
            zf.write(
                directory / self.executable, self.executable
            )  # add main executable
            if self.setup_executable:
                zf.write(
                    directory / self.setup_executable, self.setup_executable
                )  # add setup executable (if one is specified)
            if self.environment_files:
                for environment_file in self.environment_files:
                    zf.write(
                        directory / environment_file, environment_file
                    )  # add environment files (if any are specified)
        return archive_path

    def validate_archive(self, archive_path: Path) -> None:
        """Validate Experiment archive.

        Args:
            archive_path (Path): Path of the Experiment's archive

        Raises:
            ArchiveValidationError: If the archive's contents do not match the ExperimentDefinition.
        """
        with ZipFile(archive_path, mode="r") as zf:
            contents = zf.namelist()
            if EXPERIMENT_DEFINITION_NAME not in contents:
                msg = "Archive does not contain Experiment definition"
                raise ArchiveValidationError(reason=msg)
            with zf.open(EXPERIMENT_DEFINITION_NAME, "r") as f:
                archive_definition = ExperimentDefinition.model_validate(
                    load(f).unwrap(), strict=True
                )
                if archive_definition != self:
                    msg = "Experiment definition in archive is different"
                    raise ArchiveValidationError(reason=msg)

            if self.executable not in contents:
                msg = "Archive does not contain main executable"
                raise ArchiveValidationError(reason=msg)
            if self.setup_executable and self.setup_executable not in contents:
                msg = "Archive does not contain setup executable"
                raise ArchiveValidationError(reason=msg)
            if self.environment_files:
                for env_file in self.environment_files:
                    if env_file not in contents:
                        msg = f"Archive does not contain environment file {env_file}"
                        raise ArchiveValidationError(reason=msg)


class Experiment(BaseModel):
    """A parameterised experiment.

    Container for a list of Runs generated from the experiment's parameter cross-product during
    initialisation.

    Attributes:
        definition (ExperimentDefinition): Experiment metadata.
        eid (int): Unique experiment identifier. Integer representation of a UUID4, chosen for
            JSON/TOML serialisability.
        name (str): Human-readable experiment name. Does not have to be unique.
        active_state (ActiveState): Current active state. See ``ActiveState`` for semantics.
        success_state (SuccessState): Current success state. See ``SuccessState`` for semantics.
        runs (list[Run]): Runs generated from the parameter cross-product.
    """

    definition: ExperimentDefinition
    eid: int
    name: str
    active_state: ActiveState
    success_state: SuccessState
    runs: list[Run]

    def __str__(self) -> str:
        """Return a string representation of the Experiment."""
        return f"Experiment({self.name})"

    def __hash__(self) -> int:
        """Compute the hash of the Experiment."""
        return hash(self.eid)

    @property
    def active(self) -> bool:
        """Whether this Experiment is active (WAITING or RUNNING)."""
        return self.active_state in (ActiveState.WAITING, ActiveState.RUNNING)

    @property
    def waiting_runs(self) -> list[Run]:
        """Runs that have not yet been dispatched to a worker."""
        return [run for run in self.runs if run.active_state == ActiveState.WAITING]

    @classmethod
    def new(cls, definition: ExperimentDefinition) -> Experiment:
        """Create a new Experiment from an ExperimentDefinition.

        Args:
            definition (ExperimentDefinition): Definition to create the experiment from.

        Returns:
            Experiment: Newly created experiment with all runs initialised in WAITING/PENDING state.
        """
        eid = uuid4()
        active_state = ActiveState.WAITING
        success_state = SuccessState.PENDING
        runs: list[Run] = []
        expanded = _expand_parameters(definition.params)
        for index, param_set in enumerate(expanded):
            runs.append(
                Run(
                    definition=definition,
                    eid=eid.int,
                    index=index,
                    name=f"{definition.name}-{index}",
                    active_state=active_state,
                    success_state=success_state,
                    params=param_set,
                ),
            )

        return Experiment(
            definition=definition,
            eid=eid.int,
            name=definition.name,
            active_state=active_state,
            success_state=success_state,
            runs=runs,
        )

    def recalculate_state(self) -> None:
        """Recompute this Experiment's state from the current state of all its Runs."""
        if all(run.active_state == ActiveState.WAITING for run in self.runs):
            # The Experiment's state is WAITING iff all Runs are WAITING
            self.active_state = ActiveState.WAITING
        elif all(run.active_state == ActiveState.FINISHED for run in self.runs):
            # The Experiment's state is FINISHED iff all Runs are FINISHED
            self.active_state = ActiveState.FINISHED
        else:
            # The Experiment's state is RUNNING if at least one Run is RUNNING or if all Runs are either WAITING or FINISHED
            self.active_state = ActiveState.RUNNING

        if all(run.success_state == SuccessState.SUCCESS for run in self.runs):
            # The Experiment's state is SUCCESS iff all Runs are SUCCESS
            self.success_state = SuccessState.SUCCESS
        elif any(run.success_state == SuccessState.FAILED for run in self.runs):
            # If any Run has failed, the entire Experiment is considered failed
            self.success_state = SuccessState.FAILED
        else:
            self.success_state = SuccessState.PENDING


class Run(BaseModel):
    """A single run of an Experiment.

    Attributes:
        definition (ExperimentDefinition): Parent experiment's definition.
        eid (int): Parent experiment's ID. Integer representation of a UUID, for serialisability.
        index (int): This run's position in the parent experiment's run list. Together with
            ``eid`` forms the unique ``RunId``.
        wid (int | None): ID of the worker this run has been dispatched to, or ``None`` if not
            yet dispatched.
        name (str): Human-readable name, generated as ``{experiment_name}-{index}``.
        active_state (ActiveState): Current active state. See ``ActiveState`` for semantics.
        success_state (SuccessState): Current success state. See ``SuccessState`` for semantics.
        params (dict[str, TOMLScalar]): Concrete parameter set for this run — one value per
            parameter from the parent experiment's parameter lists.
    """

    definition: ExperimentDefinition
    eid: int
    index: int
    wid: int | None = None
    name: str
    active_state: ActiveState
    success_state: SuccessState
    params: dict[str, TOMLScalar]

    def __str__(self) -> str:
        """Return a string representation of the Run."""
        return f"Run({self.name})"

    def __hash__(self) -> int:
        """Compute the hash of the Run."""
        return hash(self.run_id)

    @property
    def run_id(self) -> RunId:
        """Composite identifier for this Run, combining experiment ID and run index."""
        return RunId(eid=self.eid, index=self.index)

    def assemble_args(self) -> list[str]:
        """Build the argument list to pass to the executable.

        Returns:
            list[str]: Arguments in ``key=value`` form, one entry per parameter.
        """
        args: list[str] = []

        for param, value in self.params.items():
            args.append(f"{param}={value}")

        return args


class WorkerState(StrEnum):
    """Possible states for Workers.

    IDLE: Worker is not currently executing an Experiment.
    WORKING: Worker is currently executing an Experiment.
    DEAD: Worker is unreachable.
    """

    IDLE = "IDLE"
    WORKING = "WORKING"
    DEAD = "DEAD"


class WorkerData(BaseModel):
    """A registered worker.

    Attributes:
        wid (int): Unique worker identifier. Integer representation of a UUID4.
        name (str): Human-readable name. Not required to be unique, but uniqueness is encouraged.
        state (WorkerState): Current worker state. See ``WorkerState`` for semantics.
        last_check_in (float): Unix timestamp of the worker's most recent check-in.
        run (RunId | None): ID of the run currently assigned to this worker, or ``None`` if idle.
    """

    wid: int
    name: str
    state: WorkerState
    last_check_in: float
    run: RunId | None = None

    @classmethod
    def new(cls, name: str) -> WorkerData:
        """Create a new worker with a fresh UUID and IDLE state.

        Args:
            name (str): Human-readable name for the worker. Not required to be unique.

        Returns:
            WorkerData: Newly created worker in IDLE state with ``last_check_in`` set to now.
        """
        return WorkerData(
            wid=uuid4().int, name=name, state=WorkerState.IDLE, last_check_in=time()
        )
