"""Pydantic models for experiments, runs, and workers."""

from __future__ import annotations

from enum import Enum, StrEnum, auto
from itertools import product
from os import X_OK, access
from pathlib import Path
from time import time
from typing import Any
from uuid import uuid4
from zipfile import ZIP_LZMA, ZipFile

import pytimeparse2
from pydantic import BaseModel, ValidationInfo, field_validator
from tomlkit import dump, load

from mprun.custom_types import ActiveState, RunId, SuccessState, TOMLScalar
from mprun.errors import ArchiveValidationError, InvalidParametersError

EXPERIMENT_DEFINITION_NAME = "experiment_definition.toml"
EXPERIMENT_ARCHIVE_NAME = "experiment_archive.zip"


def add_path_to_archive(zf: ZipFile, name_local: Path, name_archive: Path) -> None:
    """Add a file or directory to an open ZIP archive.

    If ``name_local`` is a file, it is added directly. If it is a directory, all files within it
    are added recursively, preserving relative paths under ``name_archive``. Paths that do not
    exist are silently skipped.

    Args:
        zf (ZipFile): Open, writable ZIP archive.
        name_local (Path): Filesystem path of the file or directory to add.
        name_archive (Path): Entry name (or prefix for directories) inside the archive.
    """
    if name_local.is_file():
        zf.write(name_local, name_archive)
    elif name_local.is_dir():
        for root, _, files in name_local.walk():
            for file in files:
                file_path = root / file
                zf.write(file_path, name_archive / file_path.relative_to(name_local))


def _expand_parameters(
    params: dict[str, list[TOMLScalar]],
) -> list[dict[str, TOMLScalar]]:
    """Return the Cartesian product of all parameter lists as concrete parameter sets.

    Args:
        params (dict[str, list[TOMLScalar]]): Mapping of parameter names to their possible values.

    Returns:
        list[dict[str, TOMLScalar]]: One dict per combination, each mapping every parameter name
            to a single value. Covers all possible combinations.

    Raises:
        InvalidParametersError: If ``params`` is empty, any key is an empty string, or any
            value list is empty.
    """
    if not params:
        raise InvalidParametersError(reason="Empty parameters not allowed")

    for key, values in params.items():
        if not key:
            raise InvalidParametersError(
                reason="Parameter keys must not be empty string"
            )
        if not values:
            raise InvalidParametersError(reason="Parameter lists must not be empty")

    expanded: list[dict[str, TOMLScalar]] = []

    keys = list(params.keys())
    for values in product(*params.values()):
        expanded.append(dict(zip(keys, values, strict=True)))

    return expanded


class ValidationMode(Enum):
    """Different modes for validation of Experiments/ExperimentDefinitions.

    DATA_ONLY: Only validate Experiment data (contents of Experiment/ExperimentDefinition object).
    DATA_AND_FILES: Also validate Experiment files (check if filenames specified in Experiment actually exist).
    """

    DATA_ONLY = auto()
    DATA_AND_FILES = auto()


class ExperimentDefinition(BaseModel):
    """Minimal information needed to create a new Experiment.

    Attributes:
        name (str): Human-readable experiment name. Does not have to be unique.
        params (dict[str, list[TOMLScalar]]): Experiment parameters. Each key maps to a list of
            discrete TOML-serializable values (str, int, float, bool). Runs are generated by
            computing the Cartesian product of all parameter lists.
        iterations (int): How many iterations of each configuration should be run.
            Useful if experiments are not deterministic to filter out noise.
            Must be at least 1.
            Defaults to 1.
        executable (str): Name of the experiment's main executable. When loading from TOML, the
            file must exist in the same directory as the TOML definition.
        results (dict[str, str]): Files or directories to save after each run. Keys are paths
            on the worker's filesystem; values are the names they will have inside the results
            archive.
        timeout (int | None): Optional run timeout in seconds. If ``None``, runs may execute
            indefinitely.
        setup_executable (str | None): Optional executable to run before the main executable.
            When loading from TOML, the file must exist in the same directory as the TOML
            definition.
        environment_variables (dict[str, str] | None): Optional environment variables to set
            before executing the main executable.
        environment_files (dict[str, str] | None): Optional additional files or directories to
            copy to the worker's filesystem before execution. Each entry maps a source path
            (relative to the experiment directory) to a destination path on the worker.
    """

    name: str
    params: dict[str, list[TOMLScalar]]
    iterations: int = 1
    executable: str
    results: dict[str, str]
    timeout: int | None = None
    setup_executable: str | None = None
    environment_variables: dict[str, str] | None = None
    environment_files: dict[str, str] | None = None

    def dump_toml(self, file_path: Path) -> None:
        """Write this ExperimentDefinition to a TOML file.

        Args:
            file_path (Path): Destination path for the TOML file.
        """
        data = self.model_dump(exclude_none=True)
        with file_path.open("w", encoding="utf-8") as f:
            dump(data=data, fp=f)

    @classmethod
    def load_toml(
        cls, file_path: Path, validation_mode: ValidationMode
    ) -> ExperimentDefinition:
        """Load an ExperimentDefinition from a TOML file.

        Args:
            file_path (Path): Path to the TOML file to load.
            validation_mode (ValidationMode): Controls validation depth. See ``ValidationMode``
                for available modes.

        Returns:
            ExperimentDefinition: Parsed and validated instance.

        Raises:
            OSError: If reading the file fails.
            pydantic.ValidationError: If the file contents are not a valid ExperimentDefinition.
            ValueError: If a timeout string is present but cannot be parsed.
        """
        with file_path.open("r") as f:
            data = load(f).unwrap()

            if validation_mode == ValidationMode.DATA_ONLY:
                return cls.model_validate(data, strict=True)
            return cls.model_validate(data, strict=True, context=file_path.parent)

    @field_validator("executable", mode="after")
    @classmethod
    def validate_executable(cls, name: str, info: ValidationInfo) -> str:
        """Validate an executable name.

        When a directory path is provided via ``info.context``, checks that a file with the given
        name exists in that directory and is marked executable.

        Args:
            name (str): Executable filename only — not a full path. The full path is derived from
                ``info.context``.
            info (ValidationInfo): When provided, ``info.context`` must be a ``Path`` pointing to
                the directory containing the experiment's files.

        Returns:
            str: The validated executable name, unchanged.

        Raises:
            ValueError: If the context path is not a directory, the file does not exist, or the
                file is not marked executable.
        """
        if not isinstance(
            info.context, Path
        ):  # if no path is provided, there's no further evaluation to do.
            return name
        dir_path: Path = info.context
        if not dir_path.is_dir():  # the directory should actually be a directory...
            msg = f"{dir_path} not a directory"
            raise ValueError(msg)

        executable_path = dir_path / name
        if not executable_path.is_file(
            follow_symlinks=False
        ):  # a file with the name should exist
            msg = f"No such file: {executable_path}"
            raise ValueError(msg)
        if not access(executable_path, X_OK):  # the file should be marked executable
            msg = f"File {executable_path} not marked executable"
            raise ValueError(msg)

        return name

    @field_validator("setup_executable", mode="after")
    @classmethod
    def validate_setup(cls, name: str | None, info: ValidationInfo) -> str | None:
        """Validate the optional setup executable.

        When a name is provided, applies the same validation logic as ``validate_executable``.

        Args:
            name (str | None): Executable filename only — not a full path. ``None`` skips
                validation entirely.
            info (ValidationInfo): When provided, ``info.context`` must be a ``Path`` pointing to
                the directory containing the experiment's files.

        Returns:
            str | None: ``None`` if no name was given; otherwise the validated name, unchanged.

        Raises:
            ValueError: If the context path is not a directory, the file does not exist, or the
                file is not marked executable.
        """
        if name is None:  # if no name is given, then there's nothing to do
            return None
        return cls.validate_executable(
            name=name, info=info
        )  # if a name is given, the validation logic is the same as with the main executable.

    @field_validator("environment_files", mode="after")
    @classmethod
    def validate_env_files(
        cls, files: dict[str, str] | None, info: ValidationInfo
    ) -> dict[str, str] | None:
        """Validate the optional environment files mapping.

        Checks that each source file exists within the experiment directory. Destination paths
        are not validated.

        Args:
            files (dict[str, str] | None): Mapping of source filenames to destination paths,
                i.e. ``{file_name: copy_to}``. ``None`` skips validation entirely.
            info (ValidationInfo): When provided, ``info.context`` must be a ``Path`` pointing to
                the directory containing the experiment's files.

        Returns:
            dict[str, str] | None: ``None`` if no files were specified; otherwise the validated
                mapping, unchanged.

        Raises:
            ValueError: If the context path is not a directory or any source path does not exist.
        """
        if files is None:  # if no files were given, then there's nothing to do
            return None

        if not isinstance(
            info.context, Path
        ):  # if no path is provided, there's no further evaluation to do.
            return files
        dir_path: Path = info.context
        if not dir_path.is_dir():  # the directory should actually be a directory...
            msg = f"{dir_path} not a directory"
            raise ValueError(msg)

        for env_file in files:
            file_path = dir_path / env_file
            if not file_path.exists():
                msg = f"No such file or directory: {file_path}"
                raise ValueError(msg)

        return files

    @field_validator("iterations", mode="after")
    @classmethod
    def validate_iterations(cls, iterations: int) -> int:
        """Validate iterations.

        Value must be at least 1 to make sense.

        Args:
            iterations (int): How many iterations of each configuration should be run.

        Returns:
            int: Unchanged value, if it passes validation.

        Raises:
            ValueError: If the values is smaller than 1.
        """
        if iterations < 1:
            msg = "Iterations must be >= 1"
            raise ValueError(msg)
        return iterations

    @field_validator("timeout", mode="before")
    @classmethod
    def validate_timeout(cls, timeout: Any) -> int | None:  # noqa: ANN401
        """Validate timeout.

        User can put either ``None`` or an ``int`` or a ``str`` that describes a length (see pytimeparse2 documentation for valid strings).

        Args:
            timeout (Any): Timeout. Since this is a "before" validator, it might be anything at this point.

        Returns:
            int | None: None if the user specified None, otherwise the tiomeut as an integer.

        Raises:
            ValueError: If something is wrong with the value.
        """
        if timeout is None:
            return None
        if isinstance(timeout, int) and not isinstance(timeout, bool):
            if timeout <= 0:
                msg = "Timeout must be at least 1 second"
                raise ValueError(msg)
            return timeout
        if isinstance(timeout, str):
            parsed = pytimeparse2.parse(timeout, raise_exception=True)
            if isinstance(parsed, int):
                if parsed <= 0:
                    msg = "Timeout must be at least 1 second"
                    raise ValueError(msg)
                return parsed
            msg = f"Could not parse string to integer duration, got: {type(parsed)}"
            raise ValueError(msg)
        msg = f"timeout must be one of (None | int | str), got {type(timeout)}"
        raise ValueError(msg)

    def create_archive(self, experiment_toml: Path) -> Path:
        """Create archive for Experiment.

        Tries to create zip archive of all files specified in this ExperimentDefinition.
        Created archive will be located in same directory as files.

        Args:
            experiment_toml (Path): Path to the Experiment's TOML file. All other Experiment files need to be located in the same directory.

        Returns:
            Path: Path of the created archive.

        Raises:
            FileNotFoundError: If ``experiment_toml``, its parent directory, or any referenced file
                (``executable``, ``setup_executable``, entries in ``environment_files``) does not exist.
            PermissionError: If the archive destination directory is not writable, or any source
                file is not readable.
            OSError: For other I/O failures (e.g. disk full) during archive creation or file writes.
            lzma.LZMAError: If LZMA compression fails (rare; typically memory pressure or corrupt data).
        """
        directory = experiment_toml.parent
        archive_path = directory / EXPERIMENT_ARCHIVE_NAME
        with ZipFile(
            archive_path,
            mode="w",
            compression=ZIP_LZMA,
            allowZip64=True,
        ) as zf:
            zf.write(
                experiment_toml, EXPERIMENT_DEFINITION_NAME
            )  # add ExperimentDefinition itself
            zf.write(
                directory / self.executable, self.executable
            )  # add main executable
            if self.setup_executable:
                zf.write(
                    directory / self.setup_executable, self.setup_executable
                )  # add setup executable (if one is specified)
            if self.environment_files:
                for environment_file in self.environment_files:
                    add_path_to_archive(
                        zf, directory / environment_file, Path(environment_file)
                    )  # add environment files/directories (if any are specified)
        return archive_path

    def validate_archive(self, archive_path: Path) -> None:
        """Validate Experiment archive.

        Args:
            archive_path (Path): Path of the Experiment's archive

        Raises:
            ArchiveValidationError: If the archive's contents do not match the ExperimentDefinition.
        """
        with ZipFile(archive_path, mode="r") as zf:
            contents = zf.namelist()
            if EXPERIMENT_DEFINITION_NAME not in contents:
                msg = "Archive does not contain Experiment definition"
                raise ArchiveValidationError(reason=msg)
            with zf.open(EXPERIMENT_DEFINITION_NAME, "r") as f:
                archive_definition = ExperimentDefinition.model_validate(
                    load(f).unwrap(), strict=True
                )
                if archive_definition != self:
                    msg = "Experiment definition in archive is different"
                    raise ArchiveValidationError(reason=msg)

            if self.executable not in contents:
                msg = "Archive does not contain main executable"
                raise ArchiveValidationError(reason=msg)
            if self.setup_executable and self.setup_executable not in contents:
                msg = "Archive does not contain setup executable"
                raise ArchiveValidationError(reason=msg)
            if self.environment_files:
                for env_file in self.environment_files:
                    prefix = env_file + "/"
                    if env_file not in contents and not any(
                        c.startswith(prefix) for c in contents
                    ):
                        msg = f"Archive does not contain environment file or directory {env_file}"
                        raise ArchiveValidationError(reason=msg)


class Experiment(BaseModel):
    """A parameterised experiment.

    Container for a list of Runs generated from the experiment's parameter cross-product during
    initialisation.

    Attributes:
        definition (ExperimentDefinition): Experiment metadata.
        eid (int): Unique experiment identifier. Integer representation of a UUID4, chosen for
            JSON/TOML serialisability.
        name (str): Human-readable experiment name. Does not have to be unique.
        active_state (ActiveState): Current active state. See ``ActiveState`` for semantics.
        success_state (SuccessState): Current success state. See ``SuccessState`` for semantics.
        creation_timestamp (float): Timestamp of when this job was created.
        runs (list[list[Run]]): Runs generated from the parameter cross-product.
            Inner lists contains the configuration's iterations.
            Will always contain at least 1 Run.
    """

    definition: ExperimentDefinition
    eid: int
    name: str
    active_state: ActiveState
    success_state: SuccessState
    creation_timestamp: float
    runs: list[list[Run]]

    def __str__(self) -> str:
        """Return a string representation of the Experiment."""
        return f"Experiment({self.name})"

    def __hash__(self) -> int:
        """Compute the hash of the Experiment."""
        return hash(self.eid)

    @property
    def active(self) -> bool:
        """Whether this Experiment is active (WAITING or RUNNING)."""
        return self.active_state in (ActiveState.WAITING, ActiveState.RUNNING)

    @property
    def waiting_runs(self) -> list[Run]:
        """Runs that have not yet been dispatched to a worker."""
        return [
            run
            for runs in self.runs
            for run in runs
            if run.active_state == ActiveState.WAITING
        ]

    @property
    def started_running(self) -> float | None:
        """Timestamp of when the first Run was dispatched. None, if all Runs are still waiting."""
        start_times = [
            run.started_running
            for runs in self.runs
            for run in runs
            if run.started_running is not None
        ]
        if not start_times:
            return None
        return min(start_times)

    @property
    def finished_running(self) -> float | None:
        """Timestamp of when the last Run finished. None, if there are still Waiting/Running Runs."""
        end_times = [run.finished_running for runs in self.runs for run in runs]
        if any(timestamp is None for timestamp in end_times):
            return None
        return max([timestamp for timestamp in end_times if timestamp is not None])

    @classmethod
    def new(cls, definition: ExperimentDefinition) -> Experiment:
        """Create a new Experiment from an ExperimentDefinition.

        Args:
            definition (ExperimentDefinition): Definition to create the experiment from.

        Returns:
            Experiment: Newly created experiment with all runs initialised in WAITING/PENDING state.
        """
        eid = uuid4()
        active_state = ActiveState.WAITING
        success_state = SuccessState.PENDING
        runs: list[list[Run]] = []
        expanded = _expand_parameters(definition.params)
        for index, param_set in enumerate(expanded):
            configuration_runs: list[Run] = []
            for iteration in range(definition.iterations):
                configuration_runs.append(
                    Run(
                        definition=definition,
                        eid=eid.int,
                        index=index,
                        iteration=iteration,
                        active_state=active_state,
                        success_state=success_state,
                        params=param_set,
                    ),
                )
            runs.append(configuration_runs)

        return Experiment(
            definition=definition,
            eid=eid.int,
            name=definition.name,
            active_state=active_state,
            success_state=success_state,
            creation_timestamp=time(),
            runs=runs,
        )

    def recalculate_state(self) -> None:
        """Recompute this Experiment's state from the current state of all its Runs."""
        if all(
            run.active_state == ActiveState.WAITING
            for runs in self.runs
            for run in runs
        ):
            # The Experiment's state is WAITING iff all Runs are WAITING
            self.active_state = ActiveState.WAITING
        elif all(
            run.active_state == ActiveState.FINISHED
            for runs in self.runs
            for run in runs
        ):
            # The Experiment's state is FINISHED iff all Runs are FINISHED
            self.active_state = ActiveState.FINISHED
        else:
            # The Experiment's state is RUNNING if at least one Run is RUNNING or if all Runs are either WAITING or FINISHED
            self.active_state = ActiveState.RUNNING

        if all(
            run.success_state == SuccessState.SUCCESS
            for runs in self.runs
            for run in runs
        ):
            # The Experiment's state is SUCCESS iff all Runs are SUCCESS
            self.success_state = SuccessState.SUCCESS
        elif any(
            run.success_state == SuccessState.FAILED
            for runs in self.runs
            for run in runs
        ):
            # If any Run has failed, the entire Experiment is considered failed
            self.success_state = SuccessState.FAILED
        else:
            self.success_state = SuccessState.PENDING


class Run(BaseModel):
    """A single run of an Experiment.

    Attributes:
        definition (ExperimentDefinition): Parent experiment's definition.
        eid (int): Parent experiment's ID. Integer representation of a UUID, for serialisability.
        index (int): This run's position in the parent experiment's run list. Together with
            ``eid`` forms the unique ``RunId``.
        iteration (int): Which iteration within a certain configuration is this Run.
        wid (int | None): ID of the worker this run has been dispatched to, or ``None`` if not
            yet dispatched.
        active_state (ActiveState): Current active state. See ``ActiveState`` for semantics.
        success_state (SuccessState): Current success state. See ``SuccessState`` for semantics.
        started_running (float | None): Timestamp of when this Run was dispatched. None if it's still waiting.
        finished_running (float | None): Timestamp of when the Worker finished executing this Run. None if it's still waiting or running.
        params (dict[str, TOMLScalar]): Concrete parameter set for this run — one value per
            parameter from the parent experiment's parameter lists.
    """

    definition: ExperimentDefinition
    eid: int
    index: int
    iteration: int
    wid: int | None = None
    active_state: ActiveState
    success_state: SuccessState
    started_running: float | None = None
    finished_running: float | None = None
    params: dict[str, TOMLScalar]

    def __str__(self) -> str:
        """Return a string representation of the Run."""
        return f"Run({self.name})"

    def __hash__(self) -> int:
        """Compute the hash of the Run."""
        return hash(self.run_id)

    @property
    def run_id(self) -> RunId:
        """Composite identifier for this Run, combining experiment ID and run index."""
        return RunId(eid=self.eid, index=self.index, iteration=self.iteration)

    @property
    def name(self) -> str:
        """Human-readable name, generated as ``{experiment_name}-{index}-{iteration}``."""
        return f"{self.definition.name}-{self.index}-{self.iteration}"

    def assemble_args(self) -> list[str]:
        """Build the argument list to pass to the executable.

        Returns:
            list[str]: Arguments in ``--arg value`` form.
        """
        args: list[str] = []

        for param, value in self.params.items():
            args.append(f"--{param}")
            args.append(str(value))

        return args


class WorkerState(StrEnum):
    """Possible states for Workers.

    IDLE: Worker is not currently executing an Experiment.
    WORKING: Worker is currently executing an Experiment.
    DEAD: Worker is unreachable.
    """

    IDLE = "IDLE"
    WORKING = "WORKING"
    DEAD = "DEAD"


class WorkerData(BaseModel):
    """A registered worker.

    Attributes:
        wid (int): Unique worker identifier. Integer representation of a UUID4.
        name (str): Human-readable name. Not required to be unique, but uniqueness is encouraged.
        state (WorkerState): Current worker state. See ``WorkerState`` for semantics.
        last_check_in (float): Unix timestamp of the worker's most recent check-in.
        run (RunId | None): ID of the run currently assigned to this worker, or ``None`` if idle.
    """

    wid: int
    name: str
    state: WorkerState
    last_check_in: float
    run: RunId | None = None

    @classmethod
    def new(cls, name: str) -> WorkerData:
        """Create a new worker with a fresh UUID and IDLE state.

        Args:
            name (str): Human-readable name for the worker. Not required to be unique.

        Returns:
            WorkerData: Newly created worker in IDLE state with ``last_check_in`` set to now.
        """
        return WorkerData(
            wid=uuid4().int, name=name, state=WorkerState.IDLE, last_check_in=time()
        )
