#! /usr/bin/env python3

"""Module contains worker application."""

from dataclasses import dataclass
from logging import getLogger
from os import getenv
from sys import exit as goodbye
from time import sleep

from httpx import Client, HTTPStatusError

from mprun import SERVER_ADDRESS_ENV
from mprun.models import WorkerData

logger = getLogger(__name__)
WORKER_NAME_ENV = "MPRUN_WORKER_NAME"


@dataclass
class Worker:
    """Worker daemon.

    Attributes:
        client (Client): HTTP client pointed to the server's base URL.
        metadata (WorkerData): Metadata for this worker (generated by registration).
    """

    client: Client
    metadata: WorkerData

    @staticmethod
    def register(client: Client, name: str) -> WorkerData:
        """Register with the server.

        Args:
            client (Client): HTTP client pointed to the server's base URL.
            name (str): (Human readable) Name to register with.

        Returns:
            WorkerData: Worker data returned by the server, if registration was successful

        Raises:
            HTTPStatusError: If communication with server fails.
        """
        response = client.post("/workers", params={"name": name})
        response.raise_for_status()

        return WorkerData.model_validate(response.json())

    def checkin(self) -> None:
        """Perform checkin with server.

        Raises:
            HTTPStatusError: If communication with server fails.
        """
        response = self.client.post(f"/workers/checkin/{self.metadata.wid}")
        response.raise_for_status()

    def run(self) -> None:
        """Main loop for worker.

        Worker will periodically wake up to checkin with server and get new work if idle.
        """
        while True:
            try:
                self.checkin()
            except HTTPStatusError as err:
                logger.error(
                    "Error performing checkin with server: %s", err, exc_info=True
                )
            sleep(30)


def main() -> None:
    """Run worker."""
    server_address = getenv(SERVER_ADDRESS_ENV)
    if server_address is None:
        logger.fatal(f"Environment variable {SERVER_ADDRESS_ENV} not set!")
        goodbye(1)

    if not server_address.startswith("http://"):
        server_address = f"http://{server_address}"

    client = Client(base_url=server_address)

    name = getenv(WORKER_NAME_ENV)
    if name is None:
        logger.fatal(f"Environment variable {WORKER_NAME_ENV} not set!")
        goodbye(1)

    try:
        metadata = Worker.register(client=client, name=name)
    except HTTPStatusError as err:
        logger.fatal("Worker registration fialed: %s", err, exc_info=True)
        goodbye(1)

    worker = Worker(client=client, metadata=metadata)

    worker.run()


if __name__ == "__main__":
    main()
