#! /usr/bin/env python3

"""Module contains worker application."""

from __future__ import annotations

import asyncio
import asyncio.subprocess
import logging
from asyncio import Lock, Task, create_task, sleep, to_thread
from http import HTTPStatus
from os import environ, getenv
from pathlib import Path
from shutil import copy, copytree, unpack_archive
from tempfile import TemporaryDirectory
from time import time
from zipfile import ZIP_LZMA, ZipFile

from httpx import AsyncClient, HTTPStatusError
from typer import Exit, Option, Typer

from mprun import SERVER_ADDRESS_ENV
from mprun.errors import NoRunError
from mprun.models import (
    JOB_ARCHIVE_NAME,
    RESULTS_ARCHIVE_NAME,
    Run,
    SuccessState,
    WorkerData,
)

logger = logging.getLogger(__name__)
cli = Typer()
WORKER_NAME_ENV = "MPRUN_WORKER_NAME"
WORKER_HOME_DIR = "MPRUN_WORKER_DIRECTORY"
SLEEP_TIME = 60


class Worker:
    """Worker daemon.

    Attributes:
        http_client (AsyncClient): HTTP client pointed to the server's base URL.
        meta_data (WorkerData): Metadata for this worker (generated by registration).
        working (Run | None): Run-object if we are currently executing a run.
                              None otherwise.
        home_dir (Path): Worker home directory for storing Job archives & other data.
        archive_path (Path): Path to store archive of curent Job (if one exists).
    """

    http_client: AsyncClient
    meta_data: WorkerData
    working: Run | None
    home_dir: Path
    archive_path: Path

    _state_mutex: Lock
    _runner_task: Task

    def __init__(
        self, http_client: AsyncClient, meta_data: WorkerData, home_dir: Path
    ) -> None:
        """Initialise Worker."""
        self.http_client = http_client
        self.meta_data = meta_data
        self.working = None
        self.home_dir = home_dir
        home_dir.mkdir(parents=True, exist_ok=True)
        self.archive_path = self.home_dir / JOB_ARCHIVE_NAME
        self._state_mutex = Lock()

    @staticmethod
    async def register(client: AsyncClient, name: str) -> WorkerData:
        """Register with the server.

        Args:
            client (Client): HTTP client pointed to the server's base URL.
            name (str): (Human readable) Name to register with.

        Returns:
            WorkerData: Worker data returned by the server, if registration was successful

        Raises:
            HTTPStatusError: If communication with server fails.
        """
        logger.info("Registering with server")
        response = await client.post("/workers", params={"name": name})
        response.raise_for_status()

        worker_data = WorkerData.model_validate(response.json())
        logger.info(f"Registered successfully with ID: {worker_data.wid}")

        return worker_data

    @classmethod
    async def init(cls, server_address: str, name: str, home_directory: Path) -> Worker:
        """Initialise worker.

        Will attempt to register worker with server.
        """
        logger.info("Initialising worker")
        if not server_address.startswith("http://"):
            server_address = f"http://{server_address}"

        client = AsyncClient(base_url=server_address)
        meta_data = await Worker.register(client=client, name=name)

        return cls(http_client=client, meta_data=meta_data, home_dir=home_directory)

    async def executor_loop(self) -> None:
        """Loop for the worker's executor behaviour.

        The worker will periodically wake up and query the server for new work.
        """
        logger.info("Starting worker executor loop")
        while True:
            await sleep(SLEEP_TIME)

            async with self._state_mutex:
                if self.working is None:
                    try:
                        run = await self.get_work()
                        if run is None:
                            continue
                        self.working = run
                    except HTTPStatusError as err:
                        logger.error(
                            "Error performing checkin with server: %s",
                            err,
                            exc_info=True,
                        )
                        continue
                    state = await self.execute_run()
                    self.working.success_state = state
                    await self.upload_results()
                    self.working = None

    async def get_work(self) -> Run | None:
        """Query the server for work.

        Streams the Job archive from the server into a temporary directory and
        validates it against the Run's JobDefinition. The validated archive is
        retained on disk (under ``self.archive_path``) until the next dispatch
        replaces it; the caller is responsible for copying it elsewhere if
        persistence beyond that lifetime is required.

        Raises:
            HTTPStatusError: If communication with server fails.
            ArchiveValidationError: If the received archive does not match the Run's JobDefinition.
            zipfile.BadZipFile: If the received archive is not a valid ZIP file.
            OSError: If writing the archive to disk fails.
        """
        logger.debug("Have no work to do, asking the server...")
        async with self.http_client.stream(
            "GET", "/workers/run", params={"wid": self.meta_data.wid}
        ) as response:
            response.raise_for_status()

            if response.status_code == HTTPStatus.NO_CONTENT:
                logger.debug("Server has no work for us.")
                return None

            run = Run.model_validate_json(response.headers["X-Run"], strict=True)
            logger.debug(f"Received run: {run.rid}")

            with TemporaryDirectory(delete=True) as archive_dir:
                logger.debug("Saving Job archive")
                archive_path = Path(archive_dir) / JOB_ARCHIVE_NAME
                with archive_path.open("wb") as f:
                    async for chunk in response.aiter_bytes():
                        await to_thread(f.write, chunk)

                logger.debug("Validating Job archive")
                await to_thread(
                    run.definition.validate_archive, archive_path=archive_path
                )
                # TODO: tell the server if the archive failed validation
                logger.debug("Archive validated successfully, saving it for execution")
                await to_thread(copy, archive_path, self.archive_path)

        return run

    async def execute_run(self) -> SuccessState:
        """Execute run (asynchronously).

        If any exist, copy environment files to their specified locations.
        Then, if it exists, run the setup executable.
        Then, run the main executable.

        Returns:
            SuccessState: SUCCESS if all executables exited with status 0. FAILED otherwise
        """
        if self.working is None:
            raise NoRunError

        logger.info(f"Executing Run {self.working.rid}")
        with TemporaryDirectory(delete=True) as exec_dir:
            directory = Path(exec_dir)

            env = await self.prepare_run_environment(directory=directory)

            if self.working.definition.setup_executable is not None:
                logger.debug("Running setup executable")
                setup_stdout_path = directory / "stdout.setup"
                setup_stderr_path = directory / "stderr.setup"
                program = directory / self.working.definition.setup_executable
                with (
                    setup_stdout_path.open("wb") as setup_stdout_file,
                    setup_stderr_path.open("wb") as setup_stderr_file,
                ):
                    process = await asyncio.subprocess.create_subprocess_exec(
                        program,
                        shell=False,
                        stdout=setup_stdout_file,
                        stderr=setup_stderr_file,
                        cwd=directory,
                        env=env,
                    )
                    await process.wait()
                    if process.returncode != 0:
                        await self.collect_results(directory=directory)
                        return SuccessState.FAILED

            stdout_path = directory / "stdout"
            stderr_path = directory / "stderr"
            args = [
                directory / self.working.definition.executable,
                *self.working.assemble_args(),
            ]
            logger.debug("Running main executable")
            with (
                stdout_path.open("wb") as stdout_file,
                stderr_path.open("wb") as stderr_file,
            ):
                process = await asyncio.subprocess.create_subprocess_exec(
                    *args,
                    shell=False,
                    stdout=stdout_file,
                    stderr=stderr_file,
                    cwd=directory,
                    env=env,
                )
                await process.wait()
                await self.collect_results(directory=directory)
                if process.returncode == 0:
                    return SuccessState.SUCCESS
                return SuccessState.FAILED

    async def prepare_run_environment(self, directory: Path) -> dict[str, str]:
        """Prepare environment for Run execution."""
        if self.working is None:
            raise NoRunError

        logger.debug("Preparing for Run.")
        await to_thread(
            unpack_archive,
            filename=self.archive_path,
            extract_dir=directory,
            format="zip",
        )

        # Set execute permissions for executables
        if self.working.definition.setup_executable:
            setup_script = directory / self.working.definition.setup_executable
            await to_thread(setup_script.chmod, setup_script.stat().st_mode | 0o111)
        main_script = directory / self.working.definition.executable
        await to_thread(main_script.chmod, main_script.stat().st_mode | 0o111)

        env = environ.copy()
        if self.working.definition.environment_variables is not None:
            env.update(self.working.definition.environment_variables)

        if self.working.definition.environment_files is not None:
            logger.debug("Copying environment files to destinations")
            for (
                env_file,
                destination,
            ) in self.working.definition.environment_files.items():
                source = directory / env_file
                logger.debug(f"Copying {source} to {destination}")
                if source.is_file():
                    await to_thread(copy, source, destination)
                elif source.is_dir():
                    await to_thread(copytree, source, destination, dirs_exist_ok=True)

        return env

    async def collect_results(self, directory: Path) -> None:
        """Collect results from Job execution."""
        if self.working is None:
            raise NoRunError

        archive_path = self.home_dir / RESULTS_ARCHIVE_NAME
        with ZipFile(
            archive_path, mode="w", compression=ZIP_LZMA, allowZip64=True
        ) as zf:
            setup_stdout_path = directory / "stdout.setup"
            if await to_thread(setup_stdout_path.is_file):
                await to_thread(zf.write, setup_stdout_path, "stdout.setup")
            setup_stderr_path = directory / "stderr.setup"
            if await to_thread(setup_stderr_path.is_file):
                await to_thread(zf.write, setup_stderr_path, "stderr.setup")
            stdout_path = directory / "stdout"
            if await to_thread(stdout_path.is_file):
                await to_thread(zf.write, stdout_path, "stdout")
            stderr_path = directory / "stderr"
            if await to_thread(stderr_path.is_file):
                await to_thread(zf.write, stderr_path, "stderr")

            for result_local, result_archive in self.working.definition.results.items():
                await Worker.add_result(
                    zf=zf,
                    name_local=Path(result_local),
                    name_archive=Path(result_archive),
                )

    @staticmethod
    async def add_result(zf: ZipFile, name_local: Path, name_archive: Path) -> None:
        """Add a result to the result archive."""
        if await to_thread(name_local.is_file):
            await to_thread(zf.write, name_local, name_archive)
        elif await to_thread(name_local.is_dir):
            for root, _, files in await to_thread(name_local.walk):
                for file in files:
                    file_path = root / file
                    arcname = name_archive / file_path.relative_to(name_local)
                    await to_thread(zf.write, file_path, arcname)

    async def upload_results(self) -> None:
        """Upload Run results to server."""
        # TODO: upload results

    async def run(self) -> None:
        """Main loop for worker.

        Worker will periodically wake up to check in with server and get new work if idle.
        """
        logger.info("Starting worker main loop")
        self._runner_task = create_task(self.executor_loop())

        while True:
            await sleep(SLEEP_TIME)
            try:
                await self.check_in()
            except HTTPStatusError as err:
                logger.error(
                    "Error performing checkin with server: %s", err, exc_info=True
                )

    async def check_in(self) -> None:
        """Perform check in with server.

        Raises:
            HTTPStatusError: If communication with server fails.
        """
        logger.debug("Performing worker check in")
        response = await self.http_client.post(
            f"/workers/check_in/{self.meta_data.wid}"
        )
        response.raise_for_status()
        self.meta_data.last_check_in = time()


@cli.command()
def main(
    verbose: bool = Option(False, "-v", "--verbose", help="Enable debug logging"),
) -> None:
    """Run worker."""
    log_level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(level=log_level)

    server_address = getenv(SERVER_ADDRESS_ENV)
    if server_address is None:
        logger.fatal(f"Environment variable {SERVER_ADDRESS_ENV} not set!")
        raise Exit(1)

    name = getenv(WORKER_NAME_ENV)
    if name is None:
        logger.fatal(f"Environment variable {WORKER_NAME_ENV} not set!")
        raise Exit(1)

    home_directory = getenv(WORKER_HOME_DIR)
    if home_directory is None:
        logger.fatal(f"Environment variable {WORKER_HOME_DIR} not set!")
        raise Exit(1)
    home_directory = Path(home_directory)

    try:
        worker = asyncio.run(
            Worker.init(
                server_address=server_address, name=name, home_directory=home_directory
            )
        )
    except HTTPStatusError as err:
        logger.fatal("Worker registration failed: %s", err, exc_info=True)
        raise Exit(1) from err

    asyncio.run(worker.run())


if __name__ == "__main__":
    main()
