#! /usr/bin/env python3

"""Module contains worker application."""

from http import HTTPStatus
from logging import getLogger
from os import getenv
from pathlib import Path
from shutil import copy
from sys import exit as goodbye
from tempfile import TemporaryDirectory
from time import sleep, time

from httpx import Client, HTTPStatusError

from mprun import SERVER_ADDRESS_ENV
from mprun.models import JOB_ARCHIVE_NAME, Run, WorkerData

logger = getLogger(__name__)
WORKER_NAME_ENV = "MPRUN_WORKER_NAME"
WORKER_HOME_DIR = "MPRUN_WORKER_DIRECTORY"


class Worker:
    """Worker daemon.

    Attributes:
        http_client (Client): HTTP client pointed to the server's base URL.
        meta_data (WorkerData): Metadata for this worker (generated by registration).
        working (Run | None): Run-object if we are currently executing a run.
                              None otherwise.
    """

    http_client: Client
    meta_data: WorkerData
    working: Run | None
    home_dir: Path
    archive_path: Path

    def __init__(
        self, http_client: Client, meta_data: WorkerData, home_dir: Path
    ) -> None:
        """Initialise Worker."""
        self.http_client = http_client
        self.meta_data = meta_data
        self.working = None
        self.home_dir = home_dir
        home_dir.mkdir(parents=True, exist_ok=True)
        self.archive_path = self.home_dir / JOB_ARCHIVE_NAME

    @staticmethod
    def register(client: Client, name: str) -> WorkerData:
        """Register with the server.

        Args:
            client (Client): HTTP client pointed to the server's base URL.
            name (str): (Human readable) Name to register with.

        Returns:
            WorkerData: Worker data returned by the server, if registration was successful

        Raises:
            HTTPStatusError: If communication with server fails.
        """
        response = client.post("/workers", params={"name": name})
        response.raise_for_status()

        return WorkerData.model_validate(response.json())

    def check_in(self) -> None:
        """Perform check in with server.

        Raises:
            HTTPStatusError: If communication with server fails.
        """
        response = self.http_client.post(f"/workers/check_in/{self.meta_data.wid}")
        response.raise_for_status()
        self.meta_data.last_check_in = time()

    def get_work(self) -> None:
        """Query the server for work.

        Streams the Job archive from the server into a temporary directory and
        validates it against the Run's JobDefinition. The validated archive is
        retained on disk (under ``self.archive_path``) until the next dispatch
        replaces it; the caller is responsible for copying it elsewhere if
        persistence beyond that lifetime is required.

        Raises:
            HTTPStatusError: If communication with server fails.
            ArchiveValidationError: If the received archive does not match the Run's JobDefinition.
            zipfile.BadZipFile: If the received archive is not a valid ZIP file.
            OSError: If writing the archive to disk fails.
        """
        if self.working is not None:
            return

        with self.http_client.stream(
            "GET", "/workers/run", params={"wid": self.meta_data.wid}
        ) as response:
            response.raise_for_status()

            if response.status_code == HTTPStatus.NO_CONTENT:
                return

            run = Run.model_validate_json(response.headers["X-Run"])

            with TemporaryDirectory(delete=True) as archive_dir:
                archive_path = Path(archive_dir) / JOB_ARCHIVE_NAME
                with archive_path.open("wb") as f:
                    for chunk in response.iter_bytes():
                        f.write(chunk)
                run.definition.validate_archive(archive_path=archive_path)
                # TODO: tell the server if the archive failed validation
                copy(archive_path, self.archive_path)

        self.working = run

        # TODO: Execute run

    def run(self) -> None:
        """Main loop for worker.

        Worker will periodically wake up to check in with server and get new work if idle.
        """
        while True:
            try:
                self.check_in()
                self.get_work()
            except HTTPStatusError as err:
                logger.error(
                    "Error performing checkin with server: %s", err, exc_info=True
                )
            sleep(30)


def main() -> None:
    """Run worker."""
    server_address = getenv(SERVER_ADDRESS_ENV)
    if server_address is None:
        logger.fatal(f"Environment variable {SERVER_ADDRESS_ENV} not set!")
        goodbye(1)

    if not server_address.startswith("http://"):
        server_address = f"http://{server_address}"

    client = Client(base_url=server_address)

    name = getenv(WORKER_NAME_ENV)
    if name is None:
        logger.fatal(f"Environment variable {WORKER_NAME_ENV} not set!")
        goodbye(1)

    home_directory = getenv(WORKER_HOME_DIR)
    if home_directory is None:
        logger.fatal(f"Environment variable {WORKER_HOME_DIR} not set!")
        goodbye(1)
    home_directory = Path(home_directory)

    try:
        meta_data = Worker.register(client=client, name=name)
    except HTTPStatusError as err:
        logger.fatal("Worker registration failed: %s", err, exc_info=True)
        goodbye(1)

    worker = Worker(http_client=client, meta_data=meta_data, home_dir=home_directory)

    worker.run()


if __name__ == "__main__":
    main()
